#!/usr/bin/env ansible-playbook
# vim: noai:ts=2:sw=2:et
---

# from https://stackoverflow.com/a/35319216

# this reads the role requirements.yml and installs them locally

- hosts: localhost

  tasks:
    - file:
        path:  roles
        state: absent

    - local_action:
        command ansible-galaxy install -r requirements.yml --roles-path roles

    - lineinfile:
        dest:   .gitignore
        regexp: '^\/roles$'
        line:   '/roles'
        state:  present
